spring:
  datasource:
    url: jdbc:h2:mem:authenticator_db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
jwt:
  publicKey: dupa #classpath:app.pub
  privateKey: kupa #classpath:app.key
info:
  version: "@pom.version@"
